"""Firmware templates for Hargassner pellet boilers.

This module contains XML templates (DAQPRJ format) that define the parameter
structure for different firmware versions of Hargassner boilers.
"""

from __future__ import annotations

from typing import Final

# Firmware Templates
#
# XML templates in DAQPRJ format from Hargassner DAQ files.
# These define the structure and order of telnet message parameters
#
# To add support for a new firmware version:
# 1. Use tools/daq_parser.py to extract the DAQPRJ template from a DAQ file
# 2. Add it here with a descriptive version key (e.g., "NANO_V15X")
# 3. Update FIRMWARE_VERSIONS in const.py

FIRMWARE_TEMPLATES: Final[dict[str, str]] = {
    "V14_1HAR_q1": """<DAQPRJ><ANALOG><CHANNEL id='0' name='ZK' dop='0'/><CHANNEL id='1' name='O2' unit='%'/><CHANNEL id='2' name='Abgas' unit='°C'/><CHANNEL id='3' name='Kessel' unit='°C'/><CHANNEL id='4' name='Kesselsoll' unit='°C'/><CHANNEL id='5' name='Puff_o' unit='°C'/><CHANNEL id='6' name='Puff_u' unit='°C'/><CHANNEL id='7' name='Lambda' dop='2'/><CHANNEL id='8' name='Leist' unit='%'/><CHANNEL id='9' name='Außen' unit='°C'/><CHANNEL id='10' name='Saug' unit='mbar'/><CHANNEL id='11' name='Puffer_s_oben' unit='°C'/><CHANNEL id='12' name='Puffer_s_unten' unit='°C'/><CHANNEL id='13' name='Boiler' unit='°C'/><CHANNEL id='14' name='Boilersoll' unit='°C'/><CHANNEL id='15' name='Solar' unit='°C'/><CHANNEL id='16' name='Kollektor' unit='°C'/><CHANNEL id='17' name='Puff_aS_oben' unit='°C'/><CHANNEL id='18' name='Puff_aS_unten' unit='°C'/><CHANNEL id='19' name='Puff_Füllgrad' dop='0'/><CHANNEL id='20' name='Puffer_soll_oben' unit='°C'/><CHANNEL id='21' name='Puffer_soll_unten' unit='°C'/><CHANNEL id='22' name='Max_Anf_Kessel' unit='°C'/><CHANNEL id='23' name='HK1_VL' unit='°C'/><CHANNEL id='24' name='HK1_VLsoll' unit='°C'/><CHANNEL id='25' name='HK1_RT' unit='°C'/><CHANNEL id='26' name='HK1_RTsoll' unit='°C'/><CHANNEL id='27' name='HK2_VL' unit='°C'/><CHANNEL id='28' name='HK2_VLsoll' unit='°C'/><CHANNEL id='29' name='HK2_RT' unit='°C'/><CHANNEL id='30' name='HK2_RTsoll' unit='°C'/><CHANNEL id='31' name='HK3_VL' unit='°C'/><CHANNEL id='32' name='HK3_VLsoll' unit='°C'/><CHANNEL id='33' name='HK3_RT' unit='°C'/><CHANNEL id='34' name='HK3_RTsoll' unit='°C'/><CHANNEL id='35' name='Raumsoll_Set' unit='°C'/><CHANNEL id='36' name='HK4_VL' unit='°C'/><CHANNEL id='37' name='HK4_VLsoll' unit='°C'/><CHANNEL id='38' name='HK4_RT' unit='°C'/><CHANNEL id='39' name='HK4_RTsoll' unit='°C'/><CHANNEL id='40' name='HK1_Ventilpos' unit='%'/><CHANNEL id='41' name='HK2_Ventilpos' unit='%'/><CHANNEL id='42' name='HK3_Ventilpos' unit='%'/><CHANNEL id='43' name='HK4_Ventilpos' unit='%'/><CHANNEL id='44' name='Pellets_Vorrat_kg' unit='kg'/><CHANNEL id='45' name='Pellets_Verb_kg' dop='2' unit='kg'/><CHANNEL id='46' name='Austrag' unit='%'/><CHANNEL id='47' name='AN11' unit='°C'/><CHANNEL id='48' name='AN12' unit='°C'/><CHANNEL id='49' name='AN13' unit='°C'/><CHANNEL id='50' name='AN14' unit='°C'/><CHANNEL id='51' name='AN15' unit='°C'/><CHANNEL id='52' name='AN16' unit='°C'/><CHANNEL id='53' name='Netzteil' unit='V'/><CHANNEL id='54' name='Diff_HK1' dop='0'/><CHANNEL id='55' name='Diff_HK2' dop='0'/><CHANNEL id='56' name='Diff_HK3' dop='0'/><CHANNEL id='57' name='Diff_HK4' dop='0'/><CHANNEL id='58' name='HK1_PARTY' dop='0'/><CHANNEL id='59' name='HK1_FERIEN' dop='0'/><CHANNEL id='60' name='HK1_SPARBETRIEB' dop='0'/><CHANNEL id='61' name='HK2_PARTY' dop='0'/><CHANNEL id='62' name='HK2_FERIEN' dop='0'/><CHANNEL id='63' name='HK2_SPARBETRIEB' dop='0'/><CHANNEL id='64' name='HK3_PARTY' dop='0'/><CHANNEL id='65' name='HK3_FERIEN' dop='0'/><CHANNEL id='66' name='HK3_SPARBETRIEB' dop='0'/><CHANNEL id='67' name='HK4_PARTY' dop='0'/><CHANNEL id='68' name='HK4_FERIEN' dop='0'/><CHANNEL id='69' name='HK4_SPARBETRIEB' dop='0'/><CHANNEL id='70' name='BETRIEBSST' dop='0'/><CHANNEL id='71' name='FEHLERCODE' dop='0'/><CHANNEL id='72' name='STATUS_A' dop='0'/><CHANNEL id='73' name='STATUS_D' dop='0'/><CHANNEL id='74' name='Asche_KG' dop='1' unit='kg'/><CHANNEL id='75' name='PARTYTIME_HK1' dop='0'/><CHANNEL id='76' name='PARTYTIME_HK2' dop='0'/><CHANNEL id='77' name='PARTYTIME_HK3' dop='0'/><CHANNEL id='78' name='PARTYTIME_HK4' dop='0'/><CHANNEL id='79' name='SYSTEMZEIT_MIN' dop='0'/><CHANNEL id='80' name='SYSTEMZEIT_STD' dop='0'/><CHANNEL id='81' name='SYSTEMZEIT_TAG' dop='0'/><CHANNEL id='82' name='SYSTEMZEIT_MONAT' dop='0'/><CHANNEL id='83' name='SYSTEMZEIT_JAHR' dop='0'/><CHANNEL id='84' name='BETRIEBSST_TXT' unit='TEXT'/><CHANNEL id='85' name='Handy_Vorwahl' dop='0'/><CHANNEL id='86' name='Handy_Rufnummer' dop='0'/><CHANNEL id='87' name='TWW_Freigabe' dop='0'/><CHANNEL id='88' name='Kessel_Vorlauf' unit='°C'/><CHANNEL id='89' name='Kessel_Ruecklauf' unit='°C'/><CHANNEL id='90' name='Diff_HK5' dop='0'/><CHANNEL id='91' name='Diff_HK6' dop='0'/><CHANNEL id='92' name='Diff_HK7' dop='0'/><CHANNEL id='93' name='Diff_HK8' dop='0'/><CHANNEL id='94' name='HK5_VL' unit='°C'/><CHANNEL id='95' name='HK5_VLsoll' unit='°C'/><CHANNEL id='96' name='HK5_RT' unit='°C'/><CHANNEL id='97' name='HK5_RTsoll' unit='°C'/><CHANNEL id='98' name='HK6_VL' unit='°C'/><CHANNEL id='99' name='HK6_VLsoll' unit='°C'/><CHANNEL id='100' name='HK6_RT' unit='°C'/><CHANNEL id='101' name='HK6_RTsoll' unit='°C'/><CHANNEL id='102' name='HK7_VL' unit='°C'/><CHANNEL id='103' name='HK7_VLsoll' unit='°C'/><CHANNEL id='104' name='HK7_RT' unit='°C'/><CHANNEL id='105' name='HK7_RTsoll' unit='°C'/><CHANNEL id='106' name='HK8_VL' unit='°C'/><CHANNEL id='107' name='HK8_VLsoll' unit='°C'/><CHANNEL id='108' name='HK8_RT' unit='°C'/><CHANNEL id='109' name='HK8_RTsoll' unit='°C'/><CHANNEL id='110' name='MODBUS_STOERUNG' dop='0'/><CHANNEL id='111' name='Status' dop='0'/></ANALOG><DIGITAL><CHANNEL id='1000' name='M1_Kes_Ladepump' dop='0' bit='0'/><CHANNEL id='1001' name='M2_Boilerpumpe' dop='0' bit='1'/><CHANNEL id='1002' name='M3_Zubringer' dop='0' bit='2'/><CHANNEL id='1003' name='M4_Einschubmotor' dop='0' bit='3'/><CHANNEL id='1004' name='M5_Entaschung' dop='0' bit='4'/><CHANNEL id='1005' name='M6_E_Filter' dop='0' bit='5'/><CHANNEL id='1006' name='M7_Saugzug' dop='0' bit='6'/><CHANNEL id='1007' name='M8_Zündung' dop='0' bit='7'/><CHANNEL id='1008' name='M9_HK1_Pumpe' dop='0' bit='8'/><CHANNEL id='1009' name='M10_HK1_Mischer_Auf' dop='0' bit='9'/><CHANNEL id='1010' name='M11_HK1_Mischer_Zu' dop='0' bit='10'/><CHANNEL id='1011' name='M12_HK2_Pumpe' dop='0' bit='11'/><CHANNEL id='1012' name='M13_HK2_Mischer_Auf' dop='0' bit='12'/><CHANNEL id='1013' name='M14_HK2_Mischer_Zu' dop='0' bit='13'/><CHANNEL id='1014' name='M15_Pufferpumpe' dop='0' bit='14'/><CHANNEL id='1015' name='M16_Solar' dop='0' bit='15'/><CHANNEL id='1016' name='Stoerung' dop='0' bit='0'/><CHANNEL id='1017' name='Handbetrieb' dop='0' bit='1'/><CHANNEL id='1018' name='Automatik' dop='0' bit='2'/><CHANNEL id='1019' name='Heizen' dop='0' bit='3'/><CHANNEL id='1020' name='Boiler' dop='0' bit='4'/><CHANNEL id='1021' name='M17_HK3_Pumpe' dop='0' bit='5'/><CHANNEL id='1022' name='M18_HK3_Mischer_Auf' dop='0' bit='6'/><CHANNEL id='1023' name='M19_HK3_Mischer_Zu' dop='0' bit='7'/><CHANNEL id='1024' name='M20_HK4_Pumpe' dop='0' bit='8'/><CHANNEL id='1025' name='M21_HK4_Mischer_Auf' dop='0' bit='9'/><CHANNEL id='1026' name='M22_HK4_Mischer_Zu' dop='0' bit='10'/><CHANNEL id='1027' name='M23_Zirkulationspumpe' dop='0' bit='11'/><CHANNEL id='1028' name='HK1_Modus_Auto' dop='0' bit='12'/><CHANNEL id='1029' name='HK1_Modus_Party' dop='0' bit='13'/><CHANNEL id='1030' name='HK1_Modus_Ferien' dop='0' bit='14'/><CHANNEL id='1031' name='HK1_Modus_Sparbetrieb' dop='0' bit='15'/><CHANNEL id='1032' name='E1_Aschelade_Endschalter' dop='0' bit='0'/><CHANNEL id='1033' name='E2_Türkontaktschalter' dop='0' bit='1'/><CHANNEL id='1034' name='E3_Kesseltemp_Stoerung' dop='0' bit='2'/><CHANNEL id='1035' name='E4_Silo_Fuellstandsmelder' dop='0' bit='3'/><CHANNEL id='1036' name='E5_Ext_Anforderung' dop='0' bit='4'/><CHANNEL id='1037' name='E6_Funk_Raumthermostat' dop='0' bit='5'/><CHANNEL id='1038' name='E7_Stoermeldung_Kessel_gelb' dop='0' bit='6'/><CHANNEL id='1039' name='E8_Stoermeldung_Kessel_rot' dop='0' bit='7'/><CHANNEL id='1040' name='E9_Ext_HK1_Anforderung' dop='0' bit='8'/><CHANNEL id='1041' name='E10_Ext_HK2_Anforderung' dop='0' bit='9'/><CHANNEL id='1042' name='E11_Saugturbine_Stoerung' dop='0' bit='10'/><CHANNEL id='1043' name='E12_Fehlerstrom_Schutzschalter' dop='0' bit='11'/><CHANNEL id='1044' name='E13_Pufferspeicher_Anforderung' dop='0' bit='12'/><CHANNEL id='1045' name='E14_Ext_HK3_Anforderung' dop='0' bit='13'/><CHANNEL id='1046' name='E15_Ext_HK4_Anforderung' dop='0' bit='14'/><CHANNEL id='1047' name='E16_Pelletbehaelter_fast_leer' dop='0' bit='15'/><CHANNEL id='1048' name='HK2_Modus_Auto' dop='0' bit='0'/><CHANNEL id='1049' name='HK2_Modus_Party' dop='0' bit='1'/><CHANNEL id='1050' name='HK2_Modus_Ferien' dop='0' bit='2'/><CHANNEL id='1051' name='HK2_Modus_Sparbetrieb' dop='0' bit='3'/><CHANNEL id='1052' name='HK3_Modus_Auto' dop='0' bit='4'/><CHANNEL id='1053' name='HK3_Modus_Party' dop='0' bit='5'/><CHANNEL id='1054' name='HK3_Modus_Ferien' dop='0' bit='6'/><CHANNEL id='1055' name='HK3_Modus_Sparbetrieb' dop='0' bit='7'/><CHANNEL id='1056' name='HK4_Modus_Auto' dop='0' bit='8'/><CHANNEL id='1057' name='HK4_Modus_Party' dop='0' bit='9'/><CHANNEL id='1058' name='HK4_Modus_Ferien' dop='0' bit='10'/><CHANNEL id='1059' name='HK4_Modus_Sparbetrieb' dop='0' bit='11'/><CHANNEL id='1060' name='Stoerung_vorhanden' dop='0' bit='12'/><CHANNEL id='1061' name='M24_Reserve_1' dop='0' bit='13'/><CHANNEL id='1062' name='M25_Reserve_2' dop='0' bit='14'/><CHANNEL id='1063' name='M26_Reserve_3' dop='0' bit='15'/><CHANNEL id='1064' name='HK1_Abgesenkt' dop='0' bit='0'/><CHANNEL id='1065' name='HK1_Normal' dop='0' bit='1'/><CHANNEL id='1066' name='HK1_Party_Countdown' dop='0' bit='2'/><CHANNEL id='1067' name='HK1_Ferien_Programm' dop='0' bit='3'/><CHANNEL id='1068' name='HK1_Sommerzeit' dop='0' bit='4'/><CHANNEL id='1069' name='HK2_Abgesenkt' dop='0' bit='5'/><CHANNEL id='1070' name='HK2_Normal' dop='0' bit='6'/><CHANNEL id='1071' name='HK2_Party_Countdown' dop='0' bit='7'/><CHANNEL id='1072' name='HK2_Ferien_Programm' dop='0' bit='8'/><CHANNEL id='1073' name='HK2_Sommerzeit' dop='0' bit='9'/><CHANNEL id='1074' name='HK3_Abgesenkt' dop='0' bit='10'/><CHANNEL id='1075' name='HK3_Normal' dop='0' bit='11'/><CHANNEL id='1076' name='HK3_Party_Countdown' dop='0' bit='12'/><CHANNEL id='1077' name='HK3_Ferien_Programm' dop='0' bit='13'/><CHANNEL id='1078' name='HK3_Sommerzeit' dop='0' bit='14'/><CHANNEL id='1079' name='HK4_Abgesenkt' dop='0' bit='15'/><CHANNEL id='1080' name='HK4_Normal' dop='0' bit='0'/><CHANNEL id='1081' name='HK4_Party_Countdown' dop='0' bit='1'/><CHANNEL id='1082' name='HK4_Ferien_Programm' dop='0' bit='2'/><CHANNEL id='1083' name='HK4_Sommerzeit' dop='0' bit='3'/><CHANNEL id='1084' name='M27_HK5_Pumpe' dop='0' bit='4'/><CHANNEL id='1085' name='M28_HK5_Mischer_Auf' dop='0' bit='5'/><CHANNEL id='1086' name='M29_HK5_Mischer_Zu' dop='0' bit='6'/><CHANNEL id='1087' name='M30_HK6_Pumpe' dop='0' bit='7'/><CHANNEL id='1088' name='M31_HK6_Mischer_Auf' dop='0' bit='8'/><CHANNEL id='1089' name='M32_HK6_Mischer_Zu' dop='0' bit='9'/><CHANNEL id='1090' name='M33_HK7_Pumpe' dop='0' bit='10'/><CHANNEL id='1091' name='M34_HK7_Mischer_Auf' dop='0' bit='11'/><CHANNEL id='1092' name='M35_HK7_Mischer_Zu' dop='0' bit='12'/><CHANNEL id='1093' name='M36_HK8_Pumpe' dop='0' bit='13'/><CHANNEL id='1094' name='M37_HK8_Mischer_Auf' dop='0' bit='14'/><CHANNEL id='1095' name='M38_HK8_Mischer_Zu' dop='0' bit='15'/><CHANNEL id='1096' name='HK5_Modus_Auto' dop='0' bit='0'/><CHANNEL id='1097' name='HK5_Modus_Party' dop='0' bit='1'/><CHANNEL id='1098' name='HK5_Modus_Ferien' dop='0' bit='2'/><CHANNEL id='1099' name='HK5_Modus_Sparbetrieb' dop='0' bit='3'/><CHANNEL id='1100' name='HK6_Modus_Auto' dop='0' bit='4'/><CHANNEL id='1101' name='HK6_Modus_Party' dop='0' bit='5'/><CHANNEL id='1102' name='HK6_Modus_Ferien' dop='0' bit='6'/><CHANNEL id='1103' name='HK6_Modus_Sparbetrieb' dop='0' bit='7'/><CHANNEL id='1104' name='HK7_Modus_Auto' dop='0' bit='8'/><CHANNEL id='1105' name='HK7_Modus_Party' dop='0' bit='9'/><CHANNEL id='1106' name='HK7_Modus_Ferien' dop='0' bit='10'/><CHANNEL id='1107' name='HK7_Modus_Sparbetrieb' dop='0' bit='11'/><CHANNEL id='1108' name='HK8_Modus_Auto' dop='0' bit='12'/><CHANNEL id='1109' name='HK8_Modus_Party' dop='0' bit='13'/><CHANNEL id='1110' name='HK8_Modus_Ferien' dop='0' bit='14'/><CHANNEL id='1111' name='HK8_Modus_Sparbetrieb' dop='0' bit='15'/></DIGITAL></DAQPRJ>""",
}

# Complete parameter descriptions for all parameters in DAQPRJ templates
# Format: {"parameter_name": {"en": "English description", "de": "Deutsche Beschreibung"}}
PARAMETER_DESCRIPTIONS: Final[dict[str, dict[str, str]]] = {
    # Boiler core parameters (analog 0-10)
    "ZK": {"en": "Boiler state", "de": "Kesselzustand"},
    "O2": {"en": "O2 level", "de": "O2-Gehalt"},
    "Abgas": {"en": "Smoke gas temperature", "de": "Rauchgastemperatur"},
    "Kessel": {"en": "Boiler temperature", "de": "Kesseltemperatur"},
    "Kesselsoll": {"en": "Boiler temperature target", "de": "Kesseltemperatur Soll"},
    "Puff_o": {"en": "Buffer temperature top", "de": "Puffertemperatur oben"},
    "Puff_u": {"en": "Buffer temperature bottom", "de": "Puffertemperatur unten"},
    "Lambda": {"en": "Lambda value", "de": "Lambda-Wert"},
    "Leist": {"en": "Output power", "de": "Leistung"},
    "Außen": {"en": "Outside temperature", "de": "Außentemperatur"},
    "Saug": {"en": "Draft pressure", "de": "Saugzug"},
    # Buffer temperatures (analog 11-22)
    "Puffer_s_oben": {"en": "Buffer setpoint top", "de": "Puffer Sollwert oben"},
    "Puffer_s_unten": {"en": "Buffer setpoint bottom", "de": "Puffer Sollwert unten"},
    "Boiler": {"en": "Hot water boiler temperature", "de": "Warmwasser Boilertemperatur"},
    "Boilersoll": {"en": "Hot water boiler target", "de": "Warmwasser Boiler Soll"},
    "Solar": {"en": "Solar temperature", "de": "Solartemperatur"},
    "Kollektor": {"en": "Solar collector temperature", "de": "Kollektortemperatur"},
    "Puff_aS_oben": {"en": "Buffer alternative sensor top", "de": "Puffer alternativer Sensor oben"},
    "Puff_aS_unten": {"en": "Buffer alternative sensor bottom", "de": "Puffer alternativer Sensor unten"},
    "Puff_Füllgrad": {"en": "Buffer fill level", "de": "Pufferfüllgrad"},
    "Puffer_soll_oben": {"en": "Buffer target top", "de": "Puffer Zielwert oben"},
    "Puffer_soll_unten": {"en": "Buffer target bottom", "de": "Puffer Zielwert unten"},
    "Max_Anf_Kessel": {"en": "Maximum boiler request", "de": "Maximale Kesselanforderung"},
    # Heating circuits HK1-HK4 (analog 23-43)
    "HK1_VL": {"en": "Heating circuit 1 flow temperature", "de": "Heizkreis 1 Vorlauftemperatur"},
    "HK1_VLsoll": {"en": "Heating circuit 1 flow target", "de": "Heizkreis 1 Vorlauf Soll"},
    "HK1_RT": {"en": "Heating circuit 1 room temperature", "de": "Heizkreis 1 Raumtemperatur"},
    "HK1_RTsoll": {"en": "Heating circuit 1 room target", "de": "Heizkreis 1 Raum Soll"},
    "HK2_VL": {"en": "Heating circuit 2 flow temperature", "de": "Heizkreis 2 Vorlauftemperatur"},
    "HK2_VLsoll": {"en": "Heating circuit 2 flow target", "de": "Heizkreis 2 Vorlauf Soll"},
    "HK2_RT": {"en": "Heating circuit 2 room temperature", "de": "Heizkreis 2 Raumtemperatur"},
    "HK2_RTsoll": {"en": "Heating circuit 2 room target", "de": "Heizkreis 2 Raum Soll"},
    "HK3_VL": {"en": "Heating circuit 3 flow temperature", "de": "Heizkreis 3 Vorlauftemperatur"},
    "HK3_VLsoll": {"en": "Heating circuit 3 flow target", "de": "Heizkreis 3 Vorlauf Soll"},
    "HK3_RT": {"en": "Heating circuit 3 room temperature", "de": "Heizkreis 3 Raumtemperatur"},
    "HK3_RTsoll": {"en": "Heating circuit 3 room target", "de": "Heizkreis 3 Raum Soll"},
    "Raumsoll_Set": {"en": "Room temperature setpoint", "de": "Raum Solltemperatur Einstellung"},
    "HK4_VL": {"en": "Heating circuit 4 flow temperature", "de": "Heizkreis 4 Vorlauftemperatur"},
    "HK4_VLsoll": {"en": "Heating circuit 4 flow target", "de": "Heizkreis 4 Vorlauf Soll"},
    "HK4_RT": {"en": "Heating circuit 4 room temperature", "de": "Heizkreis 4 Raumtemperatur"},
    "HK4_RTsoll": {"en": "Heating circuit 4 room target", "de": "Heizkreis 4 Raum Soll"},
    "HK1_Ventilpos": {"en": "Heating circuit 1 valve position", "de": "Heizkreis 1 Ventilposition"},
    "HK2_Ventilpos": {"en": "Heating circuit 2 valve position", "de": "Heizkreis 2 Ventilposition"},
    "HK3_Ventilpos": {"en": "Heating circuit 3 valve position", "de": "Heizkreis 3 Ventilposition"},
    "HK4_Ventilpos": {"en": "Heating circuit 4 valve position", "de": "Heizkreis 4 Ventilposition"},
    # Pellet storage (analog 44-46)
    "Pellets_Vorrat_kg": {"en": "Pellet stock", "de": "Pelletsvorrat"},
    "Pellets_Verb_kg": {"en": "Pellet consumption", "de": "Pelletsverbrauch"},
    "Austrag": {"en": "Discharge rate", "de": "Austragungsrate"},
    # Analog inputs (analog 47-53)
    "AN11": {"en": "Analog input 11", "de": "Analogeingang 11"},
    "AN12": {"en": "Analog input 12", "de": "Analogeingang 12"},
    "AN13": {"en": "Analog input 13", "de": "Analogeingang 13"},
    "AN14": {"en": "Analog input 14", "de": "Analogeingang 14"},
    "AN15": {"en": "Analog input 15", "de": "Analogeingang 15"},
    "AN16": {"en": "Analog input 16", "de": "Analogeingang 16"},
    "Netzteil": {"en": "Power supply voltage", "de": "Netzteilspannung"},
    # Heating circuit differences (analog 54-57)
    "Diff_HK1": {"en": "Heating circuit 1 differential", "de": "Heizkreis 1 Differenz"},
    "Diff_HK2": {"en": "Heating circuit 2 differential", "de": "Heizkreis 2 Differenz"},
    "Diff_HK3": {"en": "Heating circuit 3 differential", "de": "Heizkreis 3 Differenz"},
    "Diff_HK4": {"en": "Heating circuit 4 differential", "de": "Heizkreis 4 Differenz"},
    # Heating circuit modes (analog 58-69)
    "HK1_PARTY": {"en": "Heating circuit 1 party mode", "de": "Heizkreis 1 Party-Modus"},
    "HK1_FERIEN": {"en": "Heating circuit 1 vacation mode", "de": "Heizkreis 1 Ferienmodus"},
    "HK1_SPARBETRIEB": {"en": "Heating circuit 1 economy mode", "de": "Heizkreis 1 Sparbetrieb"},
    "HK2_PARTY": {"en": "Heating circuit 2 party mode", "de": "Heizkreis 2 Party-Modus"},
    "HK2_FERIEN": {"en": "Heating circuit 2 vacation mode", "de": "Heizkreis 2 Ferienmodus"},
    "HK2_SPARBETRIEB": {"en": "Heating circuit 2 economy mode", "de": "Heizkreis 2 Sparbetrieb"},
    "HK3_PARTY": {"en": "Heating circuit 3 party mode", "de": "Heizkreis 3 Party-Modus"},
    "HK3_FERIEN": {"en": "Heating circuit 3 vacation mode", "de": "Heizkreis 3 Ferienmodus"},
    "HK3_SPARBETRIEB": {"en": "Heating circuit 3 economy mode", "de": "Heizkreis 3 Sparbetrieb"},
    "HK4_PARTY": {"en": "Heating circuit 4 party mode", "de": "Heizkreis 4 Party-Modus"},
    "HK4_FERIEN": {"en": "Heating circuit 4 vacation mode", "de": "Heizkreis 4 Ferienmodus"},
    "HK4_SPARBETRIEB": {"en": "Heating circuit 4 economy mode", "de": "Heizkreis 4 Sparbetrieb"},
    # System status (analog 70-74)
    "BETRIEBSST": {"en": "Operating state", "de": "Betriebszustand"},
    "FEHLERCODE": {"en": "Error code", "de": "Fehlercode"},
    "STATUS_A": {"en": "Status A", "de": "Status A"},
    "STATUS_D": {"en": "Status D", "de": "Status D"},
    "Asche_KG": {"en": "Ash weight", "de": "Aschegewicht"},
    # Party time counters (analog 75-78)
    "PARTYTIME_HK1": {"en": "Heating circuit 1 party time remaining", "de": "Heizkreis 1 Partyzeit verbleibend"},
    "PARTYTIME_HK2": {"en": "Heating circuit 2 party time remaining", "de": "Heizkreis 2 Partyzeit verbleibend"},
    "PARTYTIME_HK3": {"en": "Heating circuit 3 party time remaining", "de": "Heizkreis 3 Partyzeit verbleibend"},
    "PARTYTIME_HK4": {"en": "Heating circuit 4 party time remaining", "de": "Heizkreis 4 Partyzeit verbleibend"},
    # System time (analog 79-84)
    "SYSTEMZEIT_MIN": {"en": "System time minutes", "de": "Systemzeit Minuten"},
    "SYSTEMZEIT_STD": {"en": "System time hours", "de": "Systemzeit Stunden"},
    "SYSTEMZEIT_TAG": {"en": "System time day", "de": "Systemzeit Tag"},
    "SYSTEMZEIT_MONAT": {"en": "System time month", "de": "Systemzeit Monat"},
    "SYSTEMZEIT_JAHR": {"en": "System time year", "de": "Systemzeit Jahr"},
    "BETRIEBSST_TXT": {"en": "Operating state text", "de": "Betriebszustand Text"},
    # Phone settings (analog 85-87)
    "Handy_Vorwahl": {"en": "Mobile phone area code", "de": "Handy Vorwahl"},
    "Handy_Rufnummer": {"en": "Mobile phone number", "de": "Handy Rufnummer"},
    "TWW_Freigabe": {"en": "Hot water enable", "de": "Warmwasser Freigabe"},
    # Boiler flow/return (analog 88-89)
    "Kessel_Vorlauf": {"en": "Boiler flow temperature", "de": "Kessel Vorlauftemperatur"},
    "Kessel_Ruecklauf": {"en": "Boiler return temperature", "de": "Kessel Rücklauftemperatur"},
    # Heating circuits HK5-HK8 differentials (analog 90-93)
    "Diff_HK5": {"en": "Heating circuit 5 differential", "de": "Heizkreis 5 Differenz"},
    "Diff_HK6": {"en": "Heating circuit 6 differential", "de": "Heizkreis 6 Differenz"},
    "Diff_HK7": {"en": "Heating circuit 7 differential", "de": "Heizkreis 7 Differenz"},
    "Diff_HK8": {"en": "Heating circuit 8 differential", "de": "Heizkreis 8 Differenz"},
    # Heating circuits HK5-HK8 temperatures (analog 94-109)
    "HK5_VL": {"en": "Heating circuit 5 flow temperature", "de": "Heizkreis 5 Vorlauftemperatur"},
    "HK5_VLsoll": {"en": "Heating circuit 5 flow target", "de": "Heizkreis 5 Vorlauf Soll"},
    "HK5_RT": {"en": "Heating circuit 5 room temperature", "de": "Heizkreis 5 Raumtemperatur"},
    "HK5_RTsoll": {"en": "Heating circuit 5 room target", "de": "Heizkreis 5 Raum Soll"},
    "HK6_VL": {"en": "Heating circuit 6 flow temperature", "de": "Heizkreis 6 Vorlauftemperatur"},
    "HK6_VLsoll": {"en": "Heating circuit 6 flow target", "de": "Heizkreis 6 Vorlauf Soll"},
    "HK6_RT": {"en": "Heating circuit 6 room temperature", "de": "Heizkreis 6 Raumtemperatur"},
    "HK6_RTsoll": {"en": "Heating circuit 6 room target", "de": "Heizkreis 6 Raum Soll"},
    "HK7_VL": {"en": "Heating circuit 7 flow temperature", "de": "Heizkreis 7 Vorlauftemperatur"},
    "HK7_VLsoll": {"en": "Heating circuit 7 flow target", "de": "Heizkreis 7 Vorlauf Soll"},
    "HK7_RT": {"en": "Heating circuit 7 room temperature", "de": "Heizkreis 7 Raumtemperatur"},
    "HK7_RTsoll": {"en": "Heating circuit 7 room target", "de": "Heizkreis 7 Raum Soll"},
    "HK8_VL": {"en": "Heating circuit 8 flow temperature", "de": "Heizkreis 8 Vorlauftemperatur"},
    "HK8_VLsoll": {"en": "Heating circuit 8 flow target", "de": "Heizkreis 8 Vorlauf Soll"},
    "HK8_RT": {"en": "Heating circuit 8 room temperature", "de": "Heizkreis 8 Raumtemperatur"},
    "HK8_RTsoll": {"en": "Heating circuit 8 room target", "de": "Heizkreis 8 Raum Soll"},
    # System status (analog 110-111)
    "MODBUS_STOERUNG": {"en": "Modbus error", "de": "Modbus Störung"},
    "Status": {"en": "System status", "de": "Systemstatus"},
    # Digital outputs - Motors and pumps (digital 1000-1015)
    "M1_Kes_Ladepump": {"en": "Boiler charging pump", "de": "Kessel Ladepumpe"},
    "M2_Boilerpumpe": {"en": "Hot water pump", "de": "Boilerpumpe"},
    "M3_Zubringer": {"en": "Feeder", "de": "Zubringer"},
    "M4_Einschubmotor": {"en": "Insert motor", "de": "Einschubmotor"},
    "M5_Entaschung": {"en": "Ash removal", "de": "Entaschung"},
    "M6_E_Filter": {"en": "E-filter", "de": "E-Filter"},
    "M7_Saugzug": {"en": "Induced draft fan", "de": "Saugzuggebläse"},
    "M8_Zündung": {"en": "Ignition", "de": "Zündung"},
    "M9_HK1_Pumpe": {"en": "Heating circuit 1 pump", "de": "Heizkreis 1 Pumpe"},
    "M10_HK1_Mischer_Auf": {"en": "Heating circuit 1 mixer open", "de": "Heizkreis 1 Mischer Auf"},
    "M11_HK1_Mischer_Zu": {"en": "Heating circuit 1 mixer close", "de": "Heizkreis 1 Mischer Zu"},
    "M12_HK2_Pumpe": {"en": "Heating circuit 2 pump", "de": "Heizkreis 2 Pumpe"},
    "M13_HK2_Mischer_Auf": {"en": "Heating circuit 2 mixer open", "de": "Heizkreis 2 Mischer Auf"},
    "M14_HK2_Mischer_Zu": {"en": "Heating circuit 2 mixer close", "de": "Heizkreis 2 Mischer Zu"},
    "M15_Pufferpumpe": {"en": "Buffer pump", "de": "Pufferpumpe"},
    "M16_Solar": {"en": "Solar pump", "de": "Solarpumpe"},
    # System states (digital 1016-1027)
    "Stoerung": {"en": "Error", "de": "Störung"},
    "Handbetrieb": {"en": "Manual mode", "de": "Handbetrieb"},
    "Automatik": {"en": "Automatic mode", "de": "Automatik"},
    "Heizen": {"en": "Heating", "de": "Heizen"},
    "M17_HK3_Pumpe": {"en": "Heating circuit 3 pump", "de": "Heizkreis 3 Pumpe"},
    "M18_HK3_Mischer_Auf": {"en": "Heating circuit 3 mixer open", "de": "Heizkreis 3 Mischer Auf"},
    "M19_HK3_Mischer_Zu": {"en": "Heating circuit 3 mixer close", "de": "Heizkreis 3 Mischer Zu"},
    "M20_HK4_Pumpe": {"en": "Heating circuit 4 pump", "de": "Heizkreis 4 Pumpe"},
    "M21_HK4_Mischer_Auf": {"en": "Heating circuit 4 mixer open", "de": "Heizkreis 4 Mischer Auf"},
    "M22_HK4_Mischer_Zu": {"en": "Heating circuit 4 mixer close", "de": "Heizkreis 4 Mischer Zu"},
    "M23_Zirkulationspumpe": {"en": "Circulation pump", "de": "Zirkulationspumpe"},
    # HK1 modes (digital 1028-1031)
    "HK1_Modus_Auto": {"en": "Heating circuit 1 mode auto", "de": "Heizkreis 1 Modus Auto"},
    "HK1_Modus_Party": {"en": "Heating circuit 1 mode party", "de": "Heizkreis 1 Modus Party"},
    "HK1_Modus_Ferien": {"en": "Heating circuit 1 mode vacation", "de": "Heizkreis 1 Modus Ferien"},
    "HK1_Modus_Sparbetrieb": {"en": "Heating circuit 1 mode economy", "de": "Heizkreis 1 Modus Sparbetrieb"},
    # Digital inputs (digital 1032-1047)
    "E1_Aschelade_Endschalter": {"en": "Ash drawer limit switch", "de": "Aschelade Endschalter"},
    "E2_Türkontaktschalter": {"en": "Door contact switch", "de": "Türkontaktschalter"},
    "E3_Kesseltemp_Stoerung": {"en": "Boiler temperature error", "de": "Kesseltemperatur Störung"},
    "E4_Silo_Fuellstandsmelder": {"en": "Silo level indicator", "de": "Silo Füllstandsmelder"},
    "E5_Ext_Anforderung": {"en": "External request", "de": "Externe Anforderung"},
    "E6_Funk_Raumthermostat": {"en": "Wireless room thermostat", "de": "Funk Raumthermostat"},
    "E7_Stoermeldung_Kessel_gelb": {"en": "Boiler error yellow", "de": "Störmeldung Kessel gelb"},
    "E8_Stoermeldung_Kessel_rot": {"en": "Boiler error red", "de": "Störmeldung Kessel rot"},
    "E9_Ext_HK1_Anforderung": {"en": "External heating circuit 1 request", "de": "Externe HK1 Anforderung"},
    "E10_Ext_HK2_Anforderung": {"en": "External heating circuit 2 request", "de": "Externe HK2 Anforderung"},
    "E11_Saugturbine_Stoerung": {"en": "Induced draft fan error", "de": "Saugturbine Störung"},
    "E12_Fehlerstrom_Schutzschalter": {"en": "Residual current circuit breaker", "de": "Fehlerstrom Schutzschalter"},
    "E13_Pufferspeicher_Anforderung": {"en": "Buffer storage request", "de": "Pufferspeicher Anforderung"},
    "E14_Ext_HK3_Anforderung": {"en": "External heating circuit 3 request", "de": "Externe HK3 Anforderung"},
    "E15_Ext_HK4_Anforderung": {"en": "External heating circuit 4 request", "de": "Externe HK4 Anforderung"},
    "E16_Pelletbehaelter_fast_leer": {"en": "Pellet container almost empty", "de": "Pelletbehälter fast leer"},
    # HK2-HK4 modes (digital 1048-1063)
    "HK2_Modus_Auto": {"en": "Heating circuit 2 mode auto", "de": "Heizkreis 2 Modus Auto"},
    "HK2_Modus_Party": {"en": "Heating circuit 2 mode party", "de": "Heizkreis 2 Modus Party"},
    "HK2_Modus_Ferien": {"en": "Heating circuit 2 mode vacation", "de": "Heizkreis 2 Modus Ferien"},
    "HK2_Modus_Sparbetrieb": {"en": "Heating circuit 2 mode economy", "de": "Heizkreis 2 Modus Sparbetrieb"},
    "HK3_Modus_Auto": {"en": "Heating circuit 3 mode auto", "de": "Heizkreis 3 Modus Auto"},
    "HK3_Modus_Party": {"en": "Heating circuit 3 mode party", "de": "Heizkreis 3 Modus Party"},
    "HK3_Modus_Ferien": {"en": "Heating circuit 3 mode vacation", "de": "Heizkreis 3 Modus Ferien"},
    "HK3_Modus_Sparbetrieb": {"en": "Heating circuit 3 mode economy", "de": "Heizkreis 3 Modus Sparbetrieb"},
    "HK4_Modus_Auto": {"en": "Heating circuit 4 mode auto", "de": "Heizkreis 4 Modus Auto"},
    "HK4_Modus_Party": {"en": "Heating circuit 4 mode party", "de": "Heizkreis 4 Modus Party"},
    "HK4_Modus_Ferien": {"en": "Heating circuit 4 mode vacation", "de": "Heizkreis 4 Modus Ferien"},
    "HK4_Modus_Sparbetrieb": {"en": "Heating circuit 4 mode economy", "de": "Heizkreis 4 Modus Sparbetrieb"},
    "Stoerung_vorhanden": {"en": "Error present", "de": "Störung vorhanden"},
    "M24_Reserve_1": {"en": "Reserve output 1", "de": "Reserve Ausgang 1"},
    "M25_Reserve_2": {"en": "Reserve output 2", "de": "Reserve Ausgang 2"},
    "M26_Reserve_3": {"en": "Reserve output 3", "de": "Reserve Ausgang 3"},
    # HK1-HK4 states (digital 1064-1083)
    "HK1_Abgesenkt": {"en": "Heating circuit 1 lowered", "de": "Heizkreis 1 Abgesenkt"},
    "HK1_Normal": {"en": "Heating circuit 1 normal", "de": "Heizkreis 1 Normal"},
    "HK1_Party_Countdown": {"en": "Heating circuit 1 party countdown", "de": "Heizkreis 1 Party Countdown"},
    "HK1_Ferien_Programm": {"en": "Heating circuit 1 vacation program", "de": "Heizkreis 1 Ferienprogramm"},
    "HK1_Sommerzeit": {"en": "Heating circuit 1 summer time", "de": "Heizkreis 1 Sommerzeit"},
    "HK2_Abgesenkt": {"en": "Heating circuit 2 lowered", "de": "Heizkreis 2 Abgesenkt"},
    "HK2_Normal": {"en": "Heating circuit 2 normal", "de": "Heizkreis 2 Normal"},
    "HK2_Party_Countdown": {"en": "Heating circuit 2 party countdown", "de": "Heizkreis 2 Party Countdown"},
    "HK2_Ferien_Programm": {"en": "Heating circuit 2 vacation program", "de": "Heizkreis 2 Ferienprogramm"},
    "HK2_Sommerzeit": {"en": "Heating circuit 2 summer time", "de": "Heizkreis 2 Sommerzeit"},
    "HK3_Abgesenkt": {"en": "Heating circuit 3 lowered", "de": "Heizkreis 3 Abgesenkt"},
    "HK3_Normal": {"en": "Heating circuit 3 normal", "de": "Heizkreis 3 Normal"},
    "HK3_Party_Countdown": {"en": "Heating circuit 3 party countdown", "de": "Heizkreis 3 Party Countdown"},
    "HK3_Ferien_Programm": {"en": "Heating circuit 3 vacation program", "de": "Heizkreis 3 Ferienprogramm"},
    "HK3_Sommerzeit": {"en": "Heating circuit 3 summer time", "de": "Heizkreis 3 Sommerzeit"},
    "HK4_Abgesenkt": {"en": "Heating circuit 4 lowered", "de": "Heizkreis 4 Abgesenkt"},
    "HK4_Normal": {"en": "Heating circuit 4 normal", "de": "Heizkreis 4 Normal"},
    "HK4_Party_Countdown": {"en": "Heating circuit 4 party countdown", "de": "Heizkreis 4 Party Countdown"},
    "HK4_Ferien_Programm": {"en": "Heating circuit 4 vacation program", "de": "Heizkreis 4 Ferienprogramm"},
    "HK4_Sommerzeit": {"en": "Heating circuit 4 summer time", "de": "Heizkreis 4 Sommerzeit"},
    # HK5-HK8 motors (digital 1084-1095)
    "M27_HK5_Pumpe": {"en": "Heating circuit 5 pump", "de": "Heizkreis 5 Pumpe"},
    "M28_HK5_Mischer_Auf": {"en": "Heating circuit 5 mixer open", "de": "Heizkreis 5 Mischer Auf"},
    "M29_HK5_Mischer_Zu": {"en": "Heating circuit 5 mixer close", "de": "Heizkreis 5 Mischer Zu"},
    "M30_HK6_Pumpe": {"en": "Heating circuit 6 pump", "de": "Heizkreis 6 Pumpe"},
    "M31_HK6_Mischer_Auf": {"en": "Heating circuit 6 mixer open", "de": "Heizkreis 6 Mischer Auf"},
    "M32_HK6_Mischer_Zu": {"en": "Heating circuit 6 mixer close", "de": "Heizkreis 6 Mischer Zu"},
    "M33_HK7_Pumpe": {"en": "Heating circuit 7 pump", "de": "Heizkreis 7 Pumpe"},
    "M34_HK7_Mischer_Auf": {"en": "Heating circuit 7 mixer open", "de": "Heizkreis 7 Mischer Auf"},
    "M35_HK7_Mischer_Zu": {"en": "Heating circuit 7 mixer close", "de": "Heizkreis 7 Mischer Zu"},
    "M36_HK8_Pumpe": {"en": "Heating circuit 8 pump", "de": "Heizkreis 8 Pumpe"},
    "M37_HK8_Mischer_Auf": {"en": "Heating circuit 8 mixer open", "de": "Heizkreis 8 Mischer Auf"},
    "M38_HK8_Mischer_Zu": {"en": "Heating circuit 8 mixer close", "de": "Heizkreis 8 Mischer Zu"},
    # HK5-HK8 modes (digital 1096-1111)
    "HK5_Modus_Auto": {"en": "Heating circuit 5 mode auto", "de": "Heizkreis 5 Modus Auto"},
    "HK5_Modus_Party": {"en": "Heating circuit 5 mode party", "de": "Heizkreis 5 Modus Party"},
    "HK5_Modus_Ferien": {"en": "Heating circuit 5 mode vacation", "de": "Heizkreis 5 Modus Ferien"},
    "HK5_Modus_Sparbetrieb": {"en": "Heating circuit 5 mode economy", "de": "Heizkreis 5 Modus Sparbetrieb"},
    "HK6_Modus_Auto": {"en": "Heating circuit 6 mode auto", "de": "Heizkreis 6 Modus Auto"},
    "HK6_Modus_Party": {"en": "Heating circuit 6 mode party", "de": "Heizkreis 6 Modus Party"},
    "HK6_Modus_Ferien": {"en": "Heating circuit 6 mode vacation", "de": "Heizkreis 6 Modus Ferien"},
    "HK6_Modus_Sparbetrieb": {"en": "Heating circuit 6 mode economy", "de": "Heizkreis 6 Modus Sparbetrieb"},
    "HK7_Modus_Auto": {"en": "Heating circuit 7 mode auto", "de": "Heizkreis 7 Modus Auto"},
    "HK7_Modus_Party": {"en": "Heating circuit 7 mode party", "de": "Heizkreis 7 Modus Party"},
    "HK7_Modus_Ferien": {"en": "Heating circuit 7 mode vacation", "de": "Heizkreis 7 Modus Ferien"},
    "HK7_Modus_Sparbetrieb": {"en": "Heating circuit 7 mode economy", "de": "Heizkreis 7 Modus Sparbetrieb"},
    "HK8_Modus_Auto": {"en": "Heating circuit 8 mode auto", "de": "Heizkreis 8 Modus Auto"},
    "HK8_Modus_Party": {"en": "Heating circuit 8 mode party", "de": "Heizkreis 8 Modus Party"},
    "HK8_Modus_Ferien": {"en": "Heating circuit 8 mode vacation", "de": "Heizkreis 8 Modus Ferien"},
    "HK8_Modus_Sparbetrieb": {"en": "Heating circuit 8 mode economy", "de": "Heizkreis 8 Modus Sparbetrieb"},
}
